### ISSUE TITLE
Add mail.default.from to config

### ISSUE THREAD

**Issue by Gomez** [mrlesmithjr/ansible-rundeck#11]
My rundeck failed to send mails. We should add this the config with good defaults:

grails.mail.default.from=rundeck@ansible_fqdn

**Comment by mrlesmithjr** [comment]
@Gomez - We could just use the existing `pri_domain_name` in `defaults/main.yml` and do something like:

```
rundeck_email_from: 'rundeck@{{ pri_domain_name }}'
```

**Comment by mrlesmithjr** [comment]
@Gomez Any other ideas on this? Just getting back around to this issue. Thanks for the info!
