### ISSUE TITLE
Missing autostart on systemd

### ISSUE THREAD

**Issue by jardleex** [mrlesmithjr/ansible-rundeck#13]
Hi, 

on Ubuntu 16.04 in faced the issue that the rundeckd service has no autostart.
Can somebody else with systemd confirm this?

If so, it would be nice to have a it configurable by this role.

Thank you very much.

**Comment by mrlesmithjr** [comment]
@jardleex I will take a look here soon and see if I can figure out what is going on.

**Comment by mrlesmithjr** [comment]
@jardleex I have definitely been able to duplicate the issue. Even at this point, a manual install seems to not work. Not sure on the solution at this point yet however.

**Comment by mrlesmithjr** [comment]
@jardleex I have been able to get Ubuntu 16.04 working with the latest `2.7.1` version with some tweaks which I still need to sort out the changes still required. However, when trying to provision a Ubuntu 14.04 instance it no longer works and generates this error `/proc/self/fd/9: 8: exec: : Permission denied` in `/var/log/rundeck/service.log`. I did find this issue which may also be related but maybe only for Ubuntu 14.04 https://github.com/rundeck/rundeck/issues/2225

**Comment by jardleex** [comment]
@mrlesmithjr 
thank you for investigation.
I've running version 2.6.11-1 of rundeck. As i expected issues when upgrading to 2.7.1 I ain't tried it yet.

At least one thing is saw was the [new jetty version](http://rundeck.org/docs/upgrading/index.html#jetty-embedded-server-was-upgraded-to-9.0.x). It changes a config line used for the _realm.properties_ file, which is useable (and used by me) with this role.

There where also changes to _/etc/rundeck/profile_ which I ain't checked yet.

**Comment by mrlesmithjr** [comment]
@jardleex Did you ever get anywhere with this? I would like to circle back around on this if you haven't yet resolved the issue. Thanks!

**Comment by jardleex** [comment]
@mrlesmithjr I build me a helper task which ensures that the service _rundeckd_ is running on my installation. Other than that no progress here.

As you also already mentioned there are some changes between Rundeck 2.6.x and 2.7.x which this role currently cant handle (autostart?, config line changes, jetty version, etc.). One option would be to dig into and make the role fly with both versions or make it 2.7.x compatible what may break it for some users. But  those  guys can use an older (aka now current) version of this role to keep it working. New users can directly start with 2.7.x.

**Comment by mrlesmithjr** [comment]
@jardleex Just realized that this was still out here. Is this still an issue or can we close this?

**Comment by jardleex** [comment]
@mrlesmithjr 

The issue that the role still does not ensure that the Rundeck service got autostart enable is still there.
As I still run with a workaround and a newer Rundeck version is out there, it would be better to review this role in general to make it compatible with the latest Rundeck version. At this step, also the autostart thing can be fixed.

Thus I'm closing this here now.
