### ISSUE TITLE
duplicate variable definiation: rundeck_install_ansible

### ISSUE THREAD

**Issue by jardleex** [mrlesmithjr/ansible-rundeck#3]
Hi,

I just got a duplicate variable definition in `defaults/main.yml` for the variable `rundeck_install_ansible`. 
Please remove one of the definitions.

Thank you.

**Comment by mrlesmithjr** [comment]
Unable to find a duplicate of the variable definition.
<img width="391" alt="screen shot 2016-10-05 at 7 49 08 am" src="https://cloud.githubusercontent.com/assets/4006149/19111989/565ce6dc-8ad0-11e6-9a93-ac4b716516aa.png">

Update! I found it and it is fixed now. Thanks for finding this @jardleex

**Comment by jardleex** [comment]
Great, thanks for the quick fixes!
